#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

BASE16_SHELL=$HOME/.homesick/repos/sl-shell/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# 
# From brew install: 
# Add the following to your zshrc to access the online help:

autoload -U compinit && compinit

fpath=( "/usr/local/share/zsh/site-functions" $fpath )

autoload -U promptinit && promptinit

prompt pure

#unalias run-help
#autoload run-help
#HELPDIR=/opt/boxen/homebrew/share/zsh/help

# boost the maven memory, useful for when running  jetty
export MAVEN_OPTS="-Duser.timezone=UTC -XX:MaxPermSize=1G -Xss4m -Xss5024k"

# List java versions
#
# /usr/libexec/java_home -V
# needed so maven uses the corrent java version.
# export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home

# export JAVA_8_HOME=$(/usr/libexec/java_home -v1.8)
# export JAVA_9_HOME=$(/usr/libexec/java_home -v9)
# export JAVA_10_HOME=$(/usr/libexec/java_home -v10)
export JAVA_11_HOME=$(/usr/libexec/java_home -v11)
# 
# alias java8='export JAVA_HOME=$JAVA_8_HOME'
# alias java9='export JAVA_HOME=$JAVA_9_HOME'
# alias java10='export JAVA_HOME=$JAVA_10_HOME'
alias java11='export JAVA_HOME=$JAVA_11_HOME'
alias cat='bat --theme=base16'

# default to Java 11
java11
# export JAVA_HOME=$(/usr/libexec/java_home -v11.0.2)

# local bin
# export PATH=$HOME/.fastlane/bin:$PATH:/Users/tsanden/Library/Python/2.7/bin:/Users/tsanden/code/dynamodump:/Users/tsanden/.gem/ruby/2.4.0/bin:$ANDROID_HOME/bin:$GOPATH/bin:/usr/local/bin

export PATH="/usr/local/bin:$PATH"

# powerline support
export PATH="/Users/tsanden/Library/Python/2.7/bin:$PATH"
export POWERLINE_CONFIG_COMMAND="/Users/tsanden/Library/Python/2.7/bin/powerline-config"

export GOPATH=$HOME/go

# flutter
export FLUTTER=/usr/local/share/flutter/bin
# export PATH=$PATH:$FLUTTER

# go
# export PATH=$PATH:/usr/local/opt/go/libexec/bin:$GOPATH/bin

# gem
export PATH="/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/2.6.0/bin:$PATH"

export ANDROID_HOME=/usr/local/opt/android-sdk
export ANDROID_NDK_HOME=/usr/local/opt/android-ndk

export FZF_DEFAULT_OPTS=--color=16

# show colors with cheat results
export CHEAT_COLORS=true
export CHEAT_COLORSCHEME=dark
export CHEAT_PATH='/usr/local/opt/cheat/libexec/lib/python3.7/site-packages/cheat/cheatsheets'
export CHEAT_PATH="$CHEAT_PATH:~/.cheat"

# FZF Options
export FZF_DEFAULT_OPTS='-m --bind ctrl-a:select-all,ctrl-d:deselect-all,ctrl-t:toggle-all'

# vim base-16 fix to use gnu-sed
PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"

# xls diff
PATH="/Users/tsanden/code/xlsx2txt/bin:$PATH"



. ~/.bin/z/z.sh

source $HOME/.zsh/aliases
source $HOME/.zsh/zsh_aliases
source $HOME/.zprivate


export EDITOR="nvim"
export VISUAL="nvim"

[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

randline () {
  # FILE='filename.txt'
  let "n=${RANDOM}%$(wc -l < $1)"
  head -n $n $1 | tail -1
}

fe() {
  local files
  IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0))
  [[ -n "$files" ]] && ${EDITOR:-vim} "${files[@]}"
}

# fd - cd to selected directory
fd() {
  local dir
  dir=$(find ${1:-.} -path '*/\.*' -prune \
                  -o -type d -print 2> /dev/null | fzf +m) &&
  cd "$dir"
}

unalias z

z() {
  if [[ -z "$*" ]]; then
    cd "$(_z -l 2>&1 | fzf +s --tac | sed 's/^[0-9,.]* *//')"
  else
    _last_z_args="$@"
    _z "$@"
  fi
}


clear

alias prettyjson='python -m json.tool'
java8 > /dev/null 2>&1

alias v=nvim
